# Generated by Django 5.0.1 on 2024-01-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_content_article_category_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_quotes',
            field=models.BooleanField(default=False),
        ),
    ]
