# Generated by Django 5.0.1 on 2024-01-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_content_is_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='article.article'),
        ),
    ]
